title: hax0r's blog
email: a@hax0r.info
description: "기술 블로그"
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
timezone: Asia/Seoul
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

